# Generated by Django 6.0.6 on 2026-07-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=150),
        ),
    ]
